######################## default configuration ####################
baseURL = "https://rahardhikautama.github.io"
title = "Rahardhika | Comparative Historical Sociology in Southeast Asia"
theme = "somrat"
# disable language
disableLanguages = [] # desable language from here

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Book Project"
URL = "#service"
weight = 3


[[menu.main]]
name = "Awards and Grants"
URL = "#testimonial"
weight = 4

[[menu.main]]
name = "Arryman Program"
URL = "https://www.edgs.northwestern.edu/arryman-program/index.html"
weight = 5

[[menu.main]]
name = "Assemblage"
URL = "https://medium.com/moving-aperture"
weight = 6

[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 7




#################### default parameters ################################
[params]
logo_light = "images/logo_rhdk.png"
logo_dark = "images/logo_rhdk-dark.png"
# Meta data
description = "This is meta description"
author = "somrat"
# contact form action
contact_form_action = "https://formspree.io/xoqlzlje" # contact form works with https://formspree.io/xoqlzlje
# Google Analitycs
google_analitycs_id = "" # your id

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.
  
############################# social site ########################
[[params.social]]
icon = "fa-facebook-f" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.facebook.com/rahardhika.utama"

[[params.social]]
icon = "fa-twitter" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/Rahardhika"

[[params.social]]
icon = "fa-instagram" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/rahardhikaa/"


[[params.social]]
icon = "fa-linkedin" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.linkedin.com/in/rahardhika-utama-2b280749/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://github.com/Somrat37/somrat); All images &copy; 2013-2020 Rahardhika Utama."


